apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: eks-ecr
    app.kubernetes.io/instance: cicd-demo-instance
    app.kubernetes.io/version: '1.0.0'
    app.kubernetes.io/managed-by: kubectl
  name: eks-ecr-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eks-ecr-demo
  template:
    metadata:
      labels:
        app: eks-ecr-demo
    spec:
      containers:
        - image: 266735821233.dkr.ecr.us-east-1.amazonaws.com/eks-ecr:latest
          imagePullPolicy: Always
          name: eks-ecr
          ports:
            - containerPort: 5000
